
# This file controls the behavior of the edge functions.
project_id = "ihijlloxwfjrrnhxqlfa"

# Define functions with their own configuration sections
[functions.esg-scraper]
verify_jwt = false

[functions.fetch-external-datasets]
verify_jwt = false

[functions.setup-esg-cron]
verify_jwt = false

# Configure Deno for edge functions
[functions]
node_modules = false
import_map = "./import_map.json"

# Server configuration - must be outside any section
port = 54335
