
# This file controls the behavior of the edge functions.
project_id = "ihijlloxwfjrrnhxqlfa"

# Define functions with their own configuration sections
[functions.esg-scraper]
verify_jwt = false

[functions.fetch-external-datasets]
verify_jwt = false

[functions.setup-esg-cron]
verify_jwt = false
